---
- name: AWS Webserver Loadbalancer
  hosts: localhost
  vars:
    vpc_name: "webserver-vpc"
    project_name: "ansible"
    region: "eu-west-1"

  tasks:
    - name: Get VPC info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc

    - name: Get Subnet info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc.vpcs[0].id }}"
      register: subnet

    - name: Get ec2 instance info
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Ansible": webserver
          instance-state-name: ["running"]
      register: ec2

    - name: Create ELB Target Group
      community.aws.elb_target_group:
        name: webservers
        region: "{{ region }}"
        protocol: http
        port: 80
        vpc_id: "{{ vpc.vpcs[0].id }}"
        health_check_path: /
        health_check_protocol: http
        successful_response_codes: "200,250-260"
        targets:
          - Id: "{{ ec2.instances[0].instance_id }}"
            Port: 80
          - Id: "{{ ec2.instances[1].instance_id }}"
            Port: 80
        state: present
        wait_timeout: 200

    - name: Create ELB
      amazon.aws.elb_application_lb:
        name: webserverelb
        region: "{{ region }}"
        security_groups:
          - "{{ ec2.instances[0].network_interfaces[0].groups[0].group_id }}"
        subnets:
          - "{{ subnet.subnets[0].subnet_id }}"
          - "{{ subnet.subnets[1].subnet_id }}"
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: webservers
        state: present
      register: elb
